### ISSUE TITLE
infinite login loop

### ISSUE THREAD

**Issue by Cariaga** [Xamarians/Xamarians.GoogleLogin#1]
Login no result stuck in SignIn.
SignIn also called twice

**Comment by Xamarians** [comment]
Hi Cariaga,

We are looking into issue and will get back to you soon.

**Comment by Xamarians** [comment]
Hi Cariaga,
It seems, you were using an invalid API key or your package name does not have the access to google API's. Follow https://www.appypie.com/faqs/how-to-create-google-api-key-for-android link to create API Key. You just have to enable Google+ API which is found in Social API section.
Don't forget to add your package name and SHA-1 Finger certificate in the API key. I have fixed that loop issue for invalid API key. We have uploaded the new version (V 1.0.2) on Nuget.
