### ISSUE TITLE
Task no end

### ISSUE THREAD

**Issue by nekszer** [Xamarians/Xamarians.GoogleLogin#2]
After select account, GoogleLoginActivity no back.,.. sorry for my bad english.

**Comment by Xamarians** [comment]
Hi nekszer

We have fixed that issue. You can check the latest version(1.0.4). It is uploaded on the nuget.

**Comment by SourabhSharma1991** [comment]
Email Id does not get from google.when login the google Name and Image successfully get but EmailID does not get.
