### ISSUE TITLE
i am getting only email and not other things. I require id, user name, profile and email id , currently i am getting only email.

### ISSUE THREAD

**Issue by Yashshree** [Xamarians/Xamarians.GoogleLogin#4]

**Comment by Xamarians** [comment]
Hi yashshree,

IGoogleLogin is returning all the fields that is id, username, profile image and email id. If you are not getting all fields then try this code.

var result = await DependencyService.Get<IGoogleLogin>().SignIn();
            if(result.IsSuccess)
            {
                imgProfile.Source = result.Image;
                var name = result.Name;
                var id = result.UserId;
            }
