### ISSUE TITLE
Compatibility issue with .NETStandard Version=v2.0

### ISSUE THREAD

**Issue by ghost** [Xamarians/Xamarians.GoogleLogin#5]
The package is incompatible with .NetStandard v2.0. With a need to support  .NET Core package this poses a challenge as it seems to support only NetFramwork Version=v4.6.1+.

**Comment by Xamarians** [comment]
> The package is incompatible with .NetStandard v2.0. With a need to support .NET Core package this poses a challenge as it seems to support only NetFramwork Version=v4.6.1+.

Hi @milimore0000,

Try to update the Xamarin.Forms and Xamarin.GooglePlayServices.Basement in your project.
